"use client";
import type { Metadata } from "next";

import { useState, useEffect } from "react";
import "./globals.css";
import { Inter, PT_Sans } from "next/font/google";
import NavBar from "./UI/layout/NavBar";
import SanityBootstrap from "../lib/SanityBootstrap";
import Scaler from "@/components/Scaler";
import WelcomeModal from "@/components/WelcomeModal";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const ptSans = PT_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-pt-sans",
});

// export const metadata: Metadata = {
//   title: "Forgewrite",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [appState, setAppState] = useState("loading");

  useEffect(() => {
    if (sessionStorage.getItem("hasVisited")) {
      setAppState("ready");
    } else {
      setAppState("welcoming");
      sessionStorage.setItem("hasVisited", "true");
    }
  }, []);

  const handleWelcomeClose = () => {
    setAppState("ready");
  };

  return (
    <html
      lang="en"
      className={`relative ${inter.className} ${ptSans.variable}`}
    >
      <body>
        {appState === "welcoming" && (
          <WelcomeModal onClose={handleWelcomeClose} />
        )}
        <SanityBootstrap />
        <Scaler />

        <div
          className="flex flex-col xl:flex-row-reverse items-center justify-center"
          id="scaler-wrapper"
          style={{ visibility: appState === "ready" ? "visible" : "hidden" }}
        >
          <NavBar />
          <main className="flex flex-col-reverse xl:flex-row p-4 pt-0 xl:p-0 w-screen xl:w-fit xl:h-full h-dvh">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
