import type { Metadata } from "next";
import "./globals.css";
import { Inter, PT_Sans } from "next/font/google";
import ClientLayout from "./clientlayout";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const ptSans = PT_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-pt-sans",
});

export const metadata: Metadata = {
  title: "Forgewrite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`relative ${inter.className} ${ptSans.variable}`}
    >
      <body>
        <main className="flex flex-col-reverse xl:flex-row p-4 pt-0 xl:p-0 w-screen xl:w-fit xl:h-full h-dvh">
          <ClientLayout>{children}</ClientLayout>
        </main>
      </body>
    </html>
  );
}
